#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use switcher_runtime::{
    ImportPreview, LoginSession, RuntimeError, RuntimeHandle, SettingsView, Snapshot,
};
use tauri::{AppHandle, Emitter, Manager, State};
use tauri_plugin_dialog::DialogExt;
use tauri_plugin_notification::NotificationExt;
use tauri_plugin_opener::OpenerExt;

type Reply<T> = Result<T, String>;

fn local_error(runtime: &RuntimeHandle, error: RuntimeError) -> String {
    error.message(&runtime.get_snapshot().settings.language)
}
fn local_text(runtime: &RuntimeHandle, english: &str, romanian: &str) -> String {
    if runtime.get_snapshot().settings.language == "ro" {
        romanian.into()
    } else {
        english.into()
    }
}

#[tauri::command]
fn get_snapshot(runtime: State<'_, RuntimeHandle>) -> Snapshot {
    runtime.get_snapshot()
}

#[tauri::command]
async fn refresh_all(runtime: State<'_, RuntimeHandle>) -> Reply<Snapshot> {
    runtime
        .refresh_all()
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn refresh_account(runtime: State<'_, RuntimeHandle>, id: String) -> Reply<Snapshot> {
    runtime
        .refresh_account(&id)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn switch_account(runtime: State<'_, RuntimeHandle>, id: String) -> Reply<Snapshot> {
    runtime
        .switch_account(&id)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn delete_account(runtime: State<'_, RuntimeHandle>, id: String) -> Reply<Snapshot> {
    runtime
        .delete_account(&id)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn set_renewal_day(
    runtime: State<'_, RuntimeHandle>,
    id: String,
    day: Option<u8>,
) -> Reply<Snapshot> {
    runtime
        .set_renewal_day(&id, day)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn update_settings(
    runtime: State<'_, RuntimeHandle>,
    settings: SettingsView,
) -> Reply<Snapshot> {
    runtime
        .update_settings(settings)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn import_current(runtime: State<'_, RuntimeHandle>) -> Reply<Snapshot> {
    runtime
        .import_current()
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn begin_login(app: AppHandle, runtime: State<'_, RuntimeHandle>) -> Reply<LoginSession> {
    let session = runtime
        .begin_login()
        .await
        .map_err(|e| local_error(&runtime, e))?;
    // The URL is generated by the fixed Claude adapter, never supplied by JavaScript.
    if app.opener().open_url(&session.url, None::<&str>).is_err() {
        let _ = runtime.cancel_login(&session.id).await;
        return Err(local_text(
            &runtime,
            "Could not open the browser. Try signing in again.",
            "Browserul nu a putut fi deschis. Reîncearcă autentificarea.",
        ));
    }
    Ok(session)
}
#[tauri::command]
async fn finish_login(
    runtime: State<'_, RuntimeHandle>,
    id: String,
    code: String,
) -> Reply<Snapshot> {
    if code.len() > 8192 || id.len() > 64 {
        return Err(local_text(
            &runtime,
            "The sign-in code is invalid.",
            "Codul de autentificare nu este valid.",
        ));
    }
    runtime
        .finish_login(&id, &code)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn cancel_login(runtime: State<'_, RuntimeHandle>, id: String) -> Reply<Snapshot> {
    runtime
        .cancel_login(&id)
        .await
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn preview_legacy_import(
    app: AppHandle,
    runtime: State<'_, RuntimeHandle>,
) -> Reply<Option<ImportPreview>> {
    let title = local_text(
        &runtime,
        "Select the ClaudeSwitch accounts folder",
        "Selectează dosarul de conturi ClaudeSwitch",
    );
    let selected = tauri::async_runtime::spawn_blocking(move || {
        app.dialog().file().set_title(title).blocking_pick_folder()
    })
    .await
    .map_err(|_| {
        local_text(
            &runtime,
            "Could not select the folder.",
            "Dosarul nu a putut fi selectat.",
        )
    })?;
    let Some(selected) = selected else {
        return Ok(None);
    };
    let path = selected.into_path().map_err(|_| {
        local_text(
            &runtime,
            "The selected folder is not local.",
            "Dosarul selectat nu este local.",
        )
    })?;
    runtime
        .preview_legacy_import(path)
        .await
        .map(Some)
        .map_err(|e| local_error(&runtime, e))
}
#[tauri::command]
async fn apply_legacy_import(
    runtime: State<'_, RuntimeHandle>,
    preview_id: String,
) -> Reply<Snapshot> {
    runtime
        .apply_legacy_import(&preview_id)
        .await
        .map_err(|e| local_error(&runtime, e))
}

fn main() {
    let demo = std::env::args().skip(1).any(|arg| arg == "--demo");
    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _, _| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.unminimize();
                let _ = window.show();
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            get_snapshot,
            refresh_all,
            refresh_account,
            switch_account,
            delete_account,
            set_renewal_day,
            update_settings,
            import_current,
            begin_login,
            finish_login,
            cancel_login,
            preview_legacy_import,
            apply_legacy_import
        ])
        .setup(move |app| {
            let runtime = if demo {
                RuntimeHandle::demo()
            } else {
                tauri::async_runtime::block_on(RuntimeHandle::open())
                    .unwrap_or_else(RuntimeHandle::unavailable)
            };
            let mut changes = runtime.subscribe();
            let mut notifications = runtime.notifications();
            let events = app.handle().clone();
            let notice_app = app.handle().clone();
            app.manage(runtime);
            tauri::WebviewWindowBuilder::from_config(app.handle(), &app.config().app.windows[0])?
                .on_navigation(|url| {
                    navigation_allowed(url.scheme(), url.host_str(), url.port_or_known_default())
                })
                .build()?;
            tauri::async_runtime::spawn(async move {
                loop {
                    match changes.recv().await {
                        Ok(snapshot) => {
                            let _ = events.emit_to("main", "snapshot_changed", snapshot);
                        }
                        Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => {
                            let snapshot = events.state::<RuntimeHandle>().get_snapshot();
                            let _ = events.emit_to("main", "snapshot_changed", snapshot);
                        }
                        Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                    }
                }
            });
            tauri::async_runtime::spawn(async move {
                loop {
                    match notifications.recv().await {
                        Ok(notice) => {
                            let _ = notice_app
                                .notification()
                                .builder()
                                .title(notice.title)
                                .body(notice.body)
                                .show();
                        }
                        Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => continue,
                        Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                    }
                }
            });
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("PrimerSwitch could not initialize its native window");
}

fn navigation_allowed(scheme: &str, host: Option<&str>, port: Option<u16>) -> bool {
    matches!(
        (scheme, host, port),
        ("tauri", Some("localhost"), None)
            | ("https", Some("tauri.localhost"), Some(443))
            | ("http", Some("tauri.localhost"), Some(80))
    ) || cfg!(debug_assertions)
        && matches!(
            (scheme, host, port),
            ("http", Some("localhost" | "127.0.0.1"), Some(1420))
        )
}

#[cfg(test)]
mod tests {
    use super::navigation_allowed;
    #[test]
    fn renderer_cannot_navigate_to_remote_or_fake_local_origins() {
        assert!(navigation_allowed("tauri", Some("localhost"), None));
        assert!(navigation_allowed(
            "http",
            Some("tauri.localhost"),
            Some(80)
        ));
        assert!(!navigation_allowed(
            "https",
            Some("platform.claude.com"),
            Some(443)
        ));
        assert!(!navigation_allowed(
            "https",
            Some("tauri.localhost.example.invalid"),
            Some(443)
        ));
        assert!(!navigation_allowed("file", None, None));
        assert!(!navigation_allowed("http", Some("localhost"), Some(9000)));
    }
}
